title: Dave Cross
description: Web Development and CI/CD Engineer · Author / Publisher · Digital Mentor
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
logo: https://davecross.co.uk/img/dave-new-sq.jpg

google_analytics: "G-4E7LRJH94L"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      image: https://davecross.co.uk/img/dave-new-sq.jpg

