remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

locale: "en-GB"

title: Leanr with Dave Cross
description: Web Development and CI/CD Engineer · Author / Publisher · Digital Mentor
logo: https://davecross.co.uk/img/dave-new-sq.jpg

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-X9P56MJ3WY"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      image: https://davecross.co.uk/img/dave-new-sq.jpg

